# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b1cf36da2c4816eaeaa3c9f338f9d63d4a6dd81c1d9c821d12f5c78dbc2672c07d9530ef87d988a352125db3fac8f3e17b13cbc3ba773b3aff47a9c154cd06

test:
  secret_key_base: 59590364bd3eb36ed8d61023677e4df4f3c00f4d551b6729e05c7a5b9dda5ae7e11a7a616193c4d26faffc26bfb0fbea5ab9bc133c355e208fe849ff8d54b96e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
